spring:
  datasource:
    url: jdbc:mysql://localhost:3306/giftshop
    password:
    username: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 8081